package org.jsoncloud.project.mt4platform.po;

public class AdminUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_user.admin_id
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_user.user_group_id
     *
     * @mbggenerated
     */
    private Integer userGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_user.id
     *
     * @return the value of tbl_admin_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_user.id
     *
     * @param id the value for tbl_admin_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_user.admin_id
     *
     * @return the value of tbl_admin_user.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_user.admin_id
     *
     * @param adminId the value for tbl_admin_user.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_user.user_group_id
     *
     * @return the value of tbl_admin_user.user_group_id
     *
     * @mbggenerated
     */
    public Integer getUserGroupId() {
        return userGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_user.user_group_id
     *
     * @param userGroupId the value for tbl_admin_user.user_group_id
     *
     * @mbggenerated
     */
    public void setUserGroupId(Integer userGroupId) {
        this.userGroupId = userGroupId;
    }
}