package org.jsoncloud.project.mt4platform.po;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.dic_key
     *
     * @mbggenerated
     */
    private String dicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.rank
     *
     * @mbggenerated
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary.editable
     *
     * @mbggenerated
     */
    private Integer editable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.id
     *
     * @return the value of tbl_dictionary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.id
     *
     * @param id the value for tbl_dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.pid
     *
     * @return the value of tbl_dictionary.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.pid
     *
     * @param pid the value for tbl_dictionary.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.dic_key
     *
     * @return the value of tbl_dictionary.dic_key
     *
     * @mbggenerated
     */
    public String getDicKey() {
        return dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.dic_key
     *
     * @param dicKey the value for tbl_dictionary.dic_key
     *
     * @mbggenerated
     */
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey == null ? null : dicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.text
     *
     * @return the value of tbl_dictionary.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.text
     *
     * @param text the value for tbl_dictionary.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.value
     *
     * @return the value of tbl_dictionary.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.value
     *
     * @param value the value for tbl_dictionary.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.rank
     *
     * @return the value of tbl_dictionary.rank
     *
     * @mbggenerated
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.rank
     *
     * @param rank the value for tbl_dictionary.rank
     *
     * @mbggenerated
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.flag
     *
     * @return the value of tbl_dictionary.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.flag
     *
     * @param flag the value for tbl_dictionary.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary.editable
     *
     * @return the value of tbl_dictionary.editable
     *
     * @mbggenerated
     */
    public Integer getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary.editable
     *
     * @param editable the value for tbl_dictionary.editable
     *
     * @mbggenerated
     */
    public void setEditable(Integer editable) {
        this.editable = editable;
    }
}