package org.jsoncloud.project.mt4platform.po;

public class Email {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_email.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_email.login_id
     *
     * @mbggenerated
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_email.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_email.server_type
     *
     * @mbggenerated
     */
    private Integer serverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_email.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_email.id
     *
     * @return the value of tbl_email.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_email.id
     *
     * @param id the value for tbl_email.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_email.login_id
     *
     * @return the value of tbl_email.login_id
     *
     * @mbggenerated
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_email.login_id
     *
     * @param loginId the value for tbl_email.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_email.password
     *
     * @return the value of tbl_email.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_email.password
     *
     * @param password the value for tbl_email.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_email.server_type
     *
     * @return the value of tbl_email.server_type
     *
     * @mbggenerated
     */
    public Integer getServerType() {
        return serverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_email.server_type
     *
     * @param serverType the value for tbl_email.server_type
     *
     * @mbggenerated
     */
    public void setServerType(Integer serverType) {
        this.serverType = serverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_email.status
     *
     * @return the value of tbl_email.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_email.status
     *
     * @param status the value for tbl_email.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}