package org.jsoncloud.project.mt4platform.po;

import java.math.BigDecimal;
import java.util.Date;

public class History {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.login_id
     *
     * @mbggenerated
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.digits
     *
     * @mbggenerated
     */
    private Integer digits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.cmd
     *
     * @mbggenerated
     */
    private Integer cmd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.volume
     *
     * @mbggenerated
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.open_time
     *
     * @mbggenerated
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.open_reserv
     *
     * @mbggenerated
     */
    private BigDecimal openReserv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.open_price
     *
     * @mbggenerated
     */
    private BigDecimal openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.sl
     *
     * @mbggenerated
     */
    private BigDecimal sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.tp
     *
     * @mbggenerated
     */
    private BigDecimal tp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.close_time
     *
     * @mbggenerated
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.close_price
     *
     * @mbggenerated
     */
    private BigDecimal closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.profit
     *
     * @mbggenerated
     */
    private BigDecimal profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.margin_rate
     *
     * @mbggenerated
     */
    private Integer marginRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.storage
     *
     * @mbggenerated
     */
    private BigDecimal storage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.taxes
     *
     * @mbggenerated
     */
    private BigDecimal taxes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.commission
     *
     * @mbggenerated
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_history.to_id
     *
     * @mbggenerated
     */
    private Integer toId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.id
     *
     * @return the value of tbl_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.id
     *
     * @param id the value for tbl_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.login_id
     *
     * @return the value of tbl_history.login_id
     *
     * @mbggenerated
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.login_id
     *
     * @param loginId the value for tbl_history.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.symbol
     *
     * @return the value of tbl_history.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.symbol
     *
     * @param symbol the value for tbl_history.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.digits
     *
     * @return the value of tbl_history.digits
     *
     * @mbggenerated
     */
    public Integer getDigits() {
        return digits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.digits
     *
     * @param digits the value for tbl_history.digits
     *
     * @mbggenerated
     */
    public void setDigits(Integer digits) {
        this.digits = digits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.cmd
     *
     * @return the value of tbl_history.cmd
     *
     * @mbggenerated
     */
    public Integer getCmd() {
        return cmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.cmd
     *
     * @param cmd the value for tbl_history.cmd
     *
     * @mbggenerated
     */
    public void setCmd(Integer cmd) {
        this.cmd = cmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.volume
     *
     * @return the value of tbl_history.volume
     *
     * @mbggenerated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.volume
     *
     * @param volume the value for tbl_history.volume
     *
     * @mbggenerated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.open_time
     *
     * @return the value of tbl_history.open_time
     *
     * @mbggenerated
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.open_time
     *
     * @param openTime the value for tbl_history.open_time
     *
     * @mbggenerated
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.open_reserv
     *
     * @return the value of tbl_history.open_reserv
     *
     * @mbggenerated
     */
    public BigDecimal getOpenReserv() {
        return openReserv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.open_reserv
     *
     * @param openReserv the value for tbl_history.open_reserv
     *
     * @mbggenerated
     */
    public void setOpenReserv(BigDecimal openReserv) {
        this.openReserv = openReserv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.open_price
     *
     * @return the value of tbl_history.open_price
     *
     * @mbggenerated
     */
    public BigDecimal getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.open_price
     *
     * @param openPrice the value for tbl_history.open_price
     *
     * @mbggenerated
     */
    public void setOpenPrice(BigDecimal openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.sl
     *
     * @return the value of tbl_history.sl
     *
     * @mbggenerated
     */
    public BigDecimal getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.sl
     *
     * @param sl the value for tbl_history.sl
     *
     * @mbggenerated
     */
    public void setSl(BigDecimal sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.tp
     *
     * @return the value of tbl_history.tp
     *
     * @mbggenerated
     */
    public BigDecimal getTp() {
        return tp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.tp
     *
     * @param tp the value for tbl_history.tp
     *
     * @mbggenerated
     */
    public void setTp(BigDecimal tp) {
        this.tp = tp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.close_time
     *
     * @return the value of tbl_history.close_time
     *
     * @mbggenerated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.close_time
     *
     * @param closeTime the value for tbl_history.close_time
     *
     * @mbggenerated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.close_price
     *
     * @return the value of tbl_history.close_price
     *
     * @mbggenerated
     */
    public BigDecimal getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.close_price
     *
     * @param closePrice the value for tbl_history.close_price
     *
     * @mbggenerated
     */
    public void setClosePrice(BigDecimal closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.profit
     *
     * @return the value of tbl_history.profit
     *
     * @mbggenerated
     */
    public BigDecimal getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.profit
     *
     * @param profit the value for tbl_history.profit
     *
     * @mbggenerated
     */
    public void setProfit(BigDecimal profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.margin_rate
     *
     * @return the value of tbl_history.margin_rate
     *
     * @mbggenerated
     */
    public Integer getMarginRate() {
        return marginRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.margin_rate
     *
     * @param marginRate the value for tbl_history.margin_rate
     *
     * @mbggenerated
     */
    public void setMarginRate(Integer marginRate) {
        this.marginRate = marginRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.create_time
     *
     * @return the value of tbl_history.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.create_time
     *
     * @param createTime the value for tbl_history.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.storage
     *
     * @return the value of tbl_history.storage
     *
     * @mbggenerated
     */
    public BigDecimal getStorage() {
        return storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.storage
     *
     * @param storage the value for tbl_history.storage
     *
     * @mbggenerated
     */
    public void setStorage(BigDecimal storage) {
        this.storage = storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.taxes
     *
     * @return the value of tbl_history.taxes
     *
     * @mbggenerated
     */
    public BigDecimal getTaxes() {
        return taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.taxes
     *
     * @param taxes the value for tbl_history.taxes
     *
     * @mbggenerated
     */
    public void setTaxes(BigDecimal taxes) {
        this.taxes = taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.commission
     *
     * @return the value of tbl_history.commission
     *
     * @mbggenerated
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.commission
     *
     * @param commission the value for tbl_history.commission
     *
     * @mbggenerated
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_history.to_id
     *
     * @return the value of tbl_history.to_id
     *
     * @mbggenerated
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_history.to_id
     *
     * @param toId the value for tbl_history.to_id
     *
     * @mbggenerated
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }
}