package org.jsoncloud.project.mt4platform.po;

import java.math.BigDecimal;
import java.util.Date;

public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.regdate
     *
     * @mbggenerated
     */
    private Date regdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.lastdate
     *
     * @mbggenerated
     */
    private Date lastdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.laverage
     *
     * @mbggenerated
     */
    private Integer laverage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.login_token
     *
     * @mbggenerated
     */
    private String loginToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.phonetype
     *
     * @mbggenerated
     */
    private Integer phonetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.pushstate
     *
     * @mbggenerated
     */
    private Integer pushstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.clientid
     *
     * @mbggenerated
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_login.sercice_type
     *
     * @mbggenerated
     */
    private Integer serciceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.id
     *
     * @return the value of tbl_login.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.id
     *
     * @param id the value for tbl_login.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.name
     *
     * @return the value of tbl_login.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.name
     *
     * @param name the value for tbl_login.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.pwd
     *
     * @return the value of tbl_login.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.pwd
     *
     * @param pwd the value for tbl_login.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.group_name
     *
     * @return the value of tbl_login.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.group_name
     *
     * @param groupName the value for tbl_login.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.regdate
     *
     * @return the value of tbl_login.regdate
     *
     * @mbggenerated
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.regdate
     *
     * @param regdate the value for tbl_login.regdate
     *
     * @mbggenerated
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.lastdate
     *
     * @return the value of tbl_login.lastdate
     *
     * @mbggenerated
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.lastdate
     *
     * @param lastdate the value for tbl_login.lastdate
     *
     * @mbggenerated
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.laverage
     *
     * @return the value of tbl_login.laverage
     *
     * @mbggenerated
     */
    public Integer getLaverage() {
        return laverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.laverage
     *
     * @param laverage the value for tbl_login.laverage
     *
     * @mbggenerated
     */
    public void setLaverage(Integer laverage) {
        this.laverage = laverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.balance
     *
     * @return the value of tbl_login.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.balance
     *
     * @param balance the value for tbl_login.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.login_token
     *
     * @return the value of tbl_login.login_token
     *
     * @mbggenerated
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.login_token
     *
     * @param loginToken the value for tbl_login.login_token
     *
     * @mbggenerated
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken == null ? null : loginToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.phonetype
     *
     * @return the value of tbl_login.phonetype
     *
     * @mbggenerated
     */
    public Integer getPhonetype() {
        return phonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.phonetype
     *
     * @param phonetype the value for tbl_login.phonetype
     *
     * @mbggenerated
     */
    public void setPhonetype(Integer phonetype) {
        this.phonetype = phonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.pushstate
     *
     * @return the value of tbl_login.pushstate
     *
     * @mbggenerated
     */
    public Integer getPushstate() {
        return pushstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.pushstate
     *
     * @param pushstate the value for tbl_login.pushstate
     *
     * @mbggenerated
     */
    public void setPushstate(Integer pushstate) {
        this.pushstate = pushstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.clientid
     *
     * @return the value of tbl_login.clientid
     *
     * @mbggenerated
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.clientid
     *
     * @param clientid the value for tbl_login.clientid
     *
     * @mbggenerated
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.token
     *
     * @return the value of tbl_login.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.token
     *
     * @param token the value for tbl_login.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_login.sercice_type
     *
     * @return the value of tbl_login.sercice_type
     *
     * @mbggenerated
     */
    public Integer getSerciceType() {
        return serciceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_login.sercice_type
     *
     * @param serciceType the value for tbl_login.sercice_type
     *
     * @mbggenerated
     */
    public void setSerciceType(Integer serciceType) {
        this.serciceType = serciceType;
    }
}