package org.jsoncloud.project.mt4platform.po;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.login_id
     *
     * @mbggenerated
     */
    private Integer loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.command
     *
     * @mbggenerated
     */
    private Integer command;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.margin
     *
     * @mbggenerated
     */
    private Integer margin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.digits
     *
     * @mbggenerated
     */
    private Integer digits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.volume
     *
     * @mbggenerated
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.stoploss
     *
     * @mbggenerated
     */
    private BigDecimal stoploss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.takeprofit
     *
     * @mbggenerated
     */
    private BigDecimal takeprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.storage
     *
     * @mbggenerated
     */
    private BigDecimal storage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.expiration
     *
     * @mbggenerated
     */
    private Date expiration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.taxes
     *
     * @mbggenerated
     */
    private BigDecimal taxes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.commission
     *
     * @mbggenerated
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.from_id
     *
     * @mbggenerated
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.id
     *
     * @return the value of tbl_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.id
     *
     * @param id the value for tbl_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.login_id
     *
     * @return the value of tbl_order.login_id
     *
     * @mbggenerated
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.login_id
     *
     * @param loginId the value for tbl_order.login_id
     *
     * @mbggenerated
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.command
     *
     * @return the value of tbl_order.command
     *
     * @mbggenerated
     */
    public Integer getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.command
     *
     * @param command the value for tbl_order.command
     *
     * @mbggenerated
     */
    public void setCommand(Integer command) {
        this.command = command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.margin
     *
     * @return the value of tbl_order.margin
     *
     * @mbggenerated
     */
    public Integer getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.margin
     *
     * @param margin the value for tbl_order.margin
     *
     * @mbggenerated
     */
    public void setMargin(Integer margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.digits
     *
     * @return the value of tbl_order.digits
     *
     * @mbggenerated
     */
    public Integer getDigits() {
        return digits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.digits
     *
     * @param digits the value for tbl_order.digits
     *
     * @mbggenerated
     */
    public void setDigits(Integer digits) {
        this.digits = digits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.comment
     *
     * @return the value of tbl_order.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.comment
     *
     * @param comment the value for tbl_order.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.volume
     *
     * @return the value of tbl_order.volume
     *
     * @mbggenerated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.volume
     *
     * @param volume the value for tbl_order.volume
     *
     * @mbggenerated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.symbol
     *
     * @return the value of tbl_order.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.symbol
     *
     * @param symbol the value for tbl_order.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.price
     *
     * @return the value of tbl_order.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.price
     *
     * @param price the value for tbl_order.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.stoploss
     *
     * @return the value of tbl_order.stoploss
     *
     * @mbggenerated
     */
    public BigDecimal getStoploss() {
        return stoploss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.stoploss
     *
     * @param stoploss the value for tbl_order.stoploss
     *
     * @mbggenerated
     */
    public void setStoploss(BigDecimal stoploss) {
        this.stoploss = stoploss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.takeprofit
     *
     * @return the value of tbl_order.takeprofit
     *
     * @mbggenerated
     */
    public BigDecimal getTakeprofit() {
        return takeprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.takeprofit
     *
     * @param takeprofit the value for tbl_order.takeprofit
     *
     * @mbggenerated
     */
    public void setTakeprofit(BigDecimal takeprofit) {
        this.takeprofit = takeprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.storage
     *
     * @return the value of tbl_order.storage
     *
     * @mbggenerated
     */
    public BigDecimal getStorage() {
        return storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.storage
     *
     * @param storage the value for tbl_order.storage
     *
     * @mbggenerated
     */
    public void setStorage(BigDecimal storage) {
        this.storage = storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.expiration
     *
     * @return the value of tbl_order.expiration
     *
     * @mbggenerated
     */
    public Date getExpiration() {
        return expiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.expiration
     *
     * @param expiration the value for tbl_order.expiration
     *
     * @mbggenerated
     */
    public void setExpiration(Date expiration) {
        this.expiration = expiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.taxes
     *
     * @return the value of tbl_order.taxes
     *
     * @mbggenerated
     */
    public BigDecimal getTaxes() {
        return taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.taxes
     *
     * @param taxes the value for tbl_order.taxes
     *
     * @mbggenerated
     */
    public void setTaxes(BigDecimal taxes) {
        this.taxes = taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.commission
     *
     * @return the value of tbl_order.commission
     *
     * @mbggenerated
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.commission
     *
     * @param commission the value for tbl_order.commission
     *
     * @mbggenerated
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.from_id
     *
     * @return the value of tbl_order.from_id
     *
     * @mbggenerated
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.from_id
     *
     * @param fromId the value for tbl_order.from_id
     *
     * @mbggenerated
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_order.create_time
     *
     * @return the value of tbl_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_order.create_time
     *
     * @param createTime the value for tbl_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}