package org.jsoncloud.project.mt4platform.po;

public class Server {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_server.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_server.server
     *
     * @mbggenerated
     */
    private String server;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_server.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_server.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_server.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_server.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_server.id
     *
     * @return the value of tbl_server.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_server.id
     *
     * @param id the value for tbl_server.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_server.server
     *
     * @return the value of tbl_server.server
     *
     * @mbggenerated
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_server.server
     *
     * @param server the value for tbl_server.server
     *
     * @mbggenerated
     */
    public void setServer(String server) {
        this.server = server == null ? null : server.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_server.username
     *
     * @return the value of tbl_server.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_server.username
     *
     * @param username the value for tbl_server.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_server.password
     *
     * @return the value of tbl_server.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_server.password
     *
     * @param password the value for tbl_server.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_server.status
     *
     * @return the value of tbl_server.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_server.status
     *
     * @param status the value for tbl_server.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_server.type
     *
     * @return the value of tbl_server.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_server.type
     *
     * @param type the value for tbl_server.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}