package org.jsoncloud.project.mt4platform.po;

public class Service {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service.service_desc
     *
     * @mbggenerated
     */
    private String serviceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_service.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service.id
     *
     * @return the value of tbl_service.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service.id
     *
     * @param id the value for tbl_service.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service.name
     *
     * @return the value of tbl_service.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service.name
     *
     * @param name the value for tbl_service.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service.service_desc
     *
     * @return the value of tbl_service.service_desc
     *
     * @mbggenerated
     */
    public String getServiceDesc() {
        return serviceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service.service_desc
     *
     * @param serviceDesc the value for tbl_service.service_desc
     *
     * @mbggenerated
     */
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc == null ? null : serviceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service.img
     *
     * @return the value of tbl_service.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service.img
     *
     * @param img the value for tbl_service.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_service.type
     *
     * @return the value of tbl_service.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_service.type
     *
     * @param type the value for tbl_service.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}