package org.jsoncloud.project.mt4platform.po;

public class Symbol {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.final_value
     *
     * @mbggenerated
     */
    private Integer finalValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.margin
     *
     * @mbggenerated
     */
    private Integer margin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.digits
     *
     * @mbggenerated
     */
    private Integer digits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_symbol.symbol_desc
     *
     * @mbggenerated
     */
    private String symbolDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.id
     *
     * @return the value of tbl_symbol.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.id
     *
     * @param id the value for tbl_symbol.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.symbol
     *
     * @return the value of tbl_symbol.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.symbol
     *
     * @param symbol the value for tbl_symbol.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.final_value
     *
     * @return the value of tbl_symbol.final_value
     *
     * @mbggenerated
     */
    public Integer getFinalValue() {
        return finalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.final_value
     *
     * @param finalValue the value for tbl_symbol.final_value
     *
     * @mbggenerated
     */
    public void setFinalValue(Integer finalValue) {
        this.finalValue = finalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.margin
     *
     * @return the value of tbl_symbol.margin
     *
     * @mbggenerated
     */
    public Integer getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.margin
     *
     * @param margin the value for tbl_symbol.margin
     *
     * @mbggenerated
     */
    public void setMargin(Integer margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.remark
     *
     * @return the value of tbl_symbol.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.remark
     *
     * @param remark the value for tbl_symbol.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.digits
     *
     * @return the value of tbl_symbol.digits
     *
     * @mbggenerated
     */
    public Integer getDigits() {
        return digits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.digits
     *
     * @param digits the value for tbl_symbol.digits
     *
     * @mbggenerated
     */
    public void setDigits(Integer digits) {
        this.digits = digits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.group_name
     *
     * @return the value of tbl_symbol.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.group_name
     *
     * @param groupName the value for tbl_symbol.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_symbol.symbol_desc
     *
     * @return the value of tbl_symbol.symbol_desc
     *
     * @mbggenerated
     */
    public String getSymbolDesc() {
        return symbolDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_symbol.symbol_desc
     *
     * @param symbolDesc the value for tbl_symbol.symbol_desc
     *
     * @mbggenerated
     */
    public void setSymbolDesc(String symbolDesc) {
        this.symbolDesc = symbolDesc == null ? null : symbolDesc.trim();
    }
}