package org.jsoncloud.project.mt4platform.po;

import java.util.Date;

public class Version {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.version_name
     *
     * @mbggenerated
     */
    private Double versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.version_code
     *
     * @mbggenerated
     */
    private Integer versionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_version.is_must
     *
     * @mbggenerated
     */
    private Integer isMust;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.id
     *
     * @return the value of tbl_version.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.id
     *
     * @param id the value for tbl_version.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.name
     *
     * @return the value of tbl_version.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.name
     *
     * @param name the value for tbl_version.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.code
     *
     * @return the value of tbl_version.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.code
     *
     * @param code the value for tbl_version.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.desc
     *
     * @return the value of tbl_version.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.desc
     *
     * @param desc the value for tbl_version.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.version_name
     *
     * @return the value of tbl_version.version_name
     *
     * @mbggenerated
     */
    public Double getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.version_name
     *
     * @param versionName the value for tbl_version.version_name
     *
     * @mbggenerated
     */
    public void setVersionName(Double versionName) {
        this.versionName = versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.version_code
     *
     * @return the value of tbl_version.version_code
     *
     * @mbggenerated
     */
    public Integer getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.version_code
     *
     * @param versionCode the value for tbl_version.version_code
     *
     * @mbggenerated
     */
    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.url
     *
     * @return the value of tbl_version.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.url
     *
     * @param url the value for tbl_version.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.flag
     *
     * @return the value of tbl_version.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.flag
     *
     * @param flag the value for tbl_version.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.update_time
     *
     * @return the value of tbl_version.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.update_time
     *
     * @param updateTime the value for tbl_version.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.create_time
     *
     * @return the value of tbl_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.create_time
     *
     * @param createTime the value for tbl_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_version.is_must
     *
     * @return the value of tbl_version.is_must
     *
     * @mbggenerated
     */
    public Integer getIsMust() {
        return isMust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_version.is_must
     *
     * @param isMust the value for tbl_version.is_must
     *
     * @mbggenerated
     */
    public void setIsMust(Integer isMust) {
        this.isMust = isMust;
    }
}