package org.jsoncloud.project.mt4platform.dao;

import org.jsoncloud.project.mt4platform.po.AdminUser;

public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_user
     *
     * @mbggenerated
     */
    int insert(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_user
     *
     * @mbggenerated
     */
    int insertSelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_user
     *
     * @mbggenerated
     */
    AdminUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_admin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdminUser record);
}