package org.jsoncloud.project.mt4platform.dao;

import org.jsoncloud.project.mt4platform.po.Email;

public interface EmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_email
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_email
     *
     * @mbggenerated
     */
    int insert(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_email
     *
     * @mbggenerated
     */
    int insertSelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_email
     *
     * @mbggenerated
     */
    Email selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Email record);
}