package org.jsoncloud.project.mt4platform.dao;

import org.jsoncloud.project.mt4platform.po.Server;

public interface ServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_server
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_server
     *
     * @mbggenerated
     */
    int insert(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_server
     *
     * @mbggenerated
     */
    int insertSelective(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_server
     *
     * @mbggenerated
     */
    Server selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_server
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Server record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_server
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Server record);
}