package org.jsoncloud.project.mt4platform.dao;

import org.jsoncloud.project.mt4platform.po.Symbol;

public interface SymbolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_symbol
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_symbol
     *
     * @mbggenerated
     */
    int insert(Symbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_symbol
     *
     * @mbggenerated
     */
    int insertSelective(Symbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_symbol
     *
     * @mbggenerated
     */
    Symbol selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_symbol
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Symbol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_symbol
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Symbol record);
}