package org.jsoncloud.project.mt4platform.dao;

import org.jsoncloud.project.mt4platform.po.Version;

public interface VersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_version
     *
     * @mbggenerated
     */
    int insert(Version record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_version
     *
     * @mbggenerated
     */
    int insertSelective(Version record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_version
     *
     * @mbggenerated
     */
    Version selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Version record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Version record);
}